---
- name: "Set common facts"
  set_fact:
    _tinc_net_path: "/etc/tinc/{{ tinc_netname }}"

- name: install epel-release
  yum:
    name: epel-release
    state: latest
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
  tags:
    - tinc_requirements
    - install

- name: refresh cache
  apt:
    update_cache: yes
  when: ansible_os_family == "debian"
  tags:
    - tinc_requirements
    - install

- name: Configure non root user
  block:
  - name: Create tinc group.
    group:
      name: "{{ tinc_group }}"
      state: present
    tags:
      - tinc_install
      - install

  - name: Create tinc user.
    user:
      name: "{{ tinc_user }}"
      group: "{{ tinc_group }}"
      groups:
        - syslog
      append: no
      system: yes
      state: present
    tags:
      - tinc_install
      - install

  - name: Add user option to commandline
    set_fact:
      tinc_extra_options: "{{ tinc_extra_options + ['--user {{ tinc_user }}'] }}"

  when: tinc_user != 'root'

- name: Create tinc log folder
  file:
    path: "{{ tinc_log_path }}"
    state: directory
    recurse: True
    owner: "{{ tinc_user }}"
    group: "{{ tinc_group }}"
    mode: u=rwx,g=r,o=

- name: install tinc
  package:
    name: tinc
    state: "{{ tinc_package_state }}"
  tags:
    - tinc_install
    - install

- name: Configure systemd.
  block:
  - name: create tinc systemd service file
    template:
      src: tinc.systemd.service.j2
      dest: /etc/systemd/system/tinc.service
    notify: Restart Service
    tags:
      - tinc_install
      - install

  - name: Enable service and reload daemon.
    systemd:
      name: "tinc"
      enabled: yes
      daemon_reload: yes

  - name: Configure logrotation.
    template:
      src: tinc.logrotate.j2
      dest: /etc/logrotate.d/tinc
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  when: ansible_service_mgr == "systemd"


- name: OpenWRT Configure tinc with UCI
  template:
    src: openwrt-tinc-uci-config.j2
    dest: /etc/config/tinc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "OpenWrt"
  tags:
    - uci
  notify:
    - Restart Service

- include: tinc_configure.yml
  tags:
    - tinc_configure
    - configure
