# Inspired by https://github.com/thisismitch/ansible-tinc
- name: "Set helper facts"
  set_fact:
    _newline: "\n"
- name: "Set commmon facts"
  set_fact:
    _tinc_hostname: "{{ inventory_hostname | replace('.','_') | replace('-','_') }}"
    _tinc_net_path: "/etc/tinc/{{ tinc_netname }}"

- name: ensure tinc netname directory exists
  file:
    path: "{{ _tinc_net_path }}/hosts"
    recurse: True
    state: directory

- name: create /etc/tinc/nets.boot file from template
  copy:
    content: "{{ tinc_netname }}"
    dest: /etc/tinc/nets.boot
  notify:
    - Restart Service

- name: ensure tinc.conf contains connection to core nodes
  template:
    src: tinc.conf.j2
    dest: "{{ _tinc_net_path }}/tinc.conf"
  notify:
    - Restart Service
  tags: connection

- name: create tinc-up file
  template:
    src: tinc-up.j2
    dest: "{{ _tinc_net_path }}/tinc-up"
    mode: 0755
  notify:
    - Restart Service

- name: create tinc-down file
  template:
    src: tinc-down.j2
    dest: "{{ _tinc_net_path }}/tinc-down"
    mode: 0755
  notify:
    - Restart Service

- name: ensure tinc hosts file binds to physical ip address
  lineinfile:
    dest: "{{ _tinc_net_path }}/hosts/{{ _tinc_hostname }}"
    regexp: "^Address ="
    line: "Address = {{ tinc_control_plane_bind_ip }}"
    create: yes
  when: inventory_hostname in groups['tinc_spine_nodes']
  notify:
    - Restart Service

- name: ensure subnet ip address is properly set in tinc host file
  blockinfile:
    path: "{{ _tinc_net_path }}/hosts/{{ _tinc_hostname }}"
    marker: "# {mark} tinc vpn ip setting in router mode ANSIBLE MANAGED BLOCK"
    block: "Subnet = {{ tinc_vpn_ip }}/32"
    create: yes
  when: tinc_mode == 'router'
  notify:
    - Restart Service

- name: Ensure custom host configuration is present
  blockinfile:
    path: "{{ _tinc_net_path }}/hosts/{{ _tinc_hostname }}"
    marker: "# {mark} custom host config ANSIBLE MANAGED BLOCK"
    block: "{{ tinc_host_conf_custom }}"
    create: yes
  when: tinc_host_conf_custom is defined
  notify:
    - Restart Service

- name: check whether /etc/tinc/netname/hosts/inventory_hostname contains "-----END RSA PUBLIC KEY-----"
  command: awk '/^-----END RSA PUBLIC KEY-----$/'  {{ _tinc_net_path }}/hosts/{{ _tinc_hostname }}
  changed_when: "public_key.stdout != '-----END RSA PUBLIC KEY-----'"
  register: public_key

# this is necessary because the public key will not be generated (non-interactively) if the private key already exists
- name: delete private key and regenerate keypair if public key is absent from tinc hosts file
  file:
    path: "{{ _tinc_net_path }}/rsa_key.priv"
    state: absent
  when: public_key.changed

- name: create tinc private key (and append public key to tincd hosts file)
  command: "tincd -n {{ tinc_netname }} -K{{ tinc_key_size }}"
  args:
    creates: "{{ _tinc_net_path }}/rsa_key.priv"
  notify:
    - Restart Service

- name: fetch tinc hosts file after key creation
  fetch:
    src: "{{ _tinc_net_path }}/hosts/{{ _tinc_hostname }}"
    dest: "fetch/{{ _tinc_hostname }}"
    flat: yes

# Note: Currently the synchronize module requires passwordless sudo
- name: sync the fetched tinc hosts files on each host
  synchronize:
    src: fetch/
    dest: "{{ _tinc_net_path }}/hosts/"
    use_ssh_args: yes
    rsync_opts:
      - "--chown=root:root"
  when: ansible_os_family != "OpenWrt"
  tags: sync
  notify:
    - Restart Service

- name: OpenWRT sync the fetched tinc hosts files on each host
  synchronize:
    src: fetch/
    dest: "{{ _tinc_net_path }}/hosts/"
    use_ssh_args: yes
    # By default rsync_path is 'sudo rsync' OpenWRT typically does not have sudo
    rsync_path: rsync
    rsync_opts:
      # rsync on OpenWRT lacks old-style --compress due to its external zlib
      - "-zz"
      - "--chown=root:root"
  tags: sync
  when: ansible_os_family == "OpenWrt"
  notify:
    - Restart Service

- name: add nodes to /etc/hosts (ansible_inventory resolves to vpn_ip)
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].tinc_vpn_ip }}"
    line: "{{ hostvars[item].tinc_vpn_ip }} {{ item }}"
    state: present
  when: hostvars[item].tinc_vpn_ip is defined
  with_items: "{{ play_hosts }}"
  tags:
    - tinc_internal_hosts

# Ensure the systemd daemon is reloaded and the service is restarted
- meta: flush_handlers

- name: ensure tinc is enabled
  service:
    name: "{{ tinc_service_name }}"
    enabled: yes
