#!/usr/bin/env bash

echo "subnet-down : #############################################################" >> /var/log/tinc.subnet.log
echo "subnet-down : NETNAME '$NETNAME'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : NAME '$NAME'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : DEVICE '$DEVICE'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : INTERFACE '$INTERFACE'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : NODE '$NODE'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : REMOTEADDRESS '$REMOTEADDRESS'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : SUBNET '$SUBNET'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : GW '$GW'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : OURNAME '$OURNAME'" | ts >> /var/log/tinc.subnet.log
echo "subnet-down : VPNNET '$VPNNET'" | ts >> /var/log/tinc.subnet.log

/usr/bin/env ip route del "$SUBNET" dev "$INTERFACE"

if [ -x "/etc/tinc/${NETNAME}/subnet-down.local" ]; then
    "/etc/tinc/${NETNAME}/subnet-down.local" "$SUBNET" "$INTERFACE"
fi